-- MySQL Script generated by MySQL Workbench
-- Sun Sep 13 21:36:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema characterbook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `characterbook` ;

-- -----------------------------------------------------
-- Schema characterbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `characterbook` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Race` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Race` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

USE `characterbook` ;

-- -----------------------------------------------------
-- Table `characterbook`.`race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `characterbook`.`race` ;

CREATE TABLE IF NOT EXISTS `characterbook`.`race` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(500) NULL DEFAULT NULL,
  `SpeedValue` INT NULL DEFAULT NULL,
  `SpeedDescription` VARCHAR(45) NULL DEFAULT NULL,
  `SizeValue` VARCHAR(45) NULL DEFAULT NULL,
  `SizeDescription` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `characterbook`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `characterbook`.`languages` ;

CREATE TABLE IF NOT EXISTS `characterbook`.`languages` (
  `id` BIGINT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `characterbook`.`races_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `characterbook`.`races_languages` ;

CREATE TABLE IF NOT EXISTS `characterbook`.`races_languages` (
  `id` BIGINT NOT NULL,
  `raceId` BIGINT NOT NULL,
  `languageId` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `raceId_idx` (`raceId` ASC) VISIBLE,
  INDEX `FK_Language_idx` (`languageId` ASC) VISIBLE,
  CONSTRAINT `FK_Race`
    FOREIGN KEY (`raceId`)
    REFERENCES `characterbook`.`race` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Language`
    FOREIGN KEY (`languageId`)
    REFERENCES `characterbook`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
